using System.Configuration;
using System.Data;
using System.Reflection;
using System.Windows;

namespace BoltFetch;

/// <summary>
/// Interaction logic for App.xaml
/// </summary>
public partial class App : System.Windows.Application
{
    protected override void OnStartup(StartupEventArgs e)
    {
        base.OnStartup(e);

        // Setup Global Exception Handlers
        this.DispatcherUnhandledException += App_DispatcherUnhandledException;
        System.Threading.Tasks.TaskScheduler.UnobservedTaskException += TaskScheduler_UnobservedTaskException;
        System.AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;

        // Dynamically set version from assembly metadata (auto-generated by csproj)
        var version = System.Reflection.Assembly.GetExecutingAssembly()
            .GetCustomAttribute<System.Reflection.AssemblyInformationalVersionAttribute>()?.InformationalVersion
            ?? "1.0.0";

        // Strip git hash suffix if present (e.g. "1.4.2603.0105+abc123" → "1.4.2603.0105")
        if (version.Contains('+')) version = version[..version.IndexOf('+')];

        this.Resources["Loc_AppVersion"] = $"Version {version}";
    }

    private void App_DispatcherUnhandledException(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e)
    {
        ShowCrashReport(e.Exception);
        e.Handled = true;
    }

    private void TaskScheduler_UnobservedTaskException(object? sender, System.Threading.Tasks.UnobservedTaskExceptionEventArgs e)
    {
        ShowCrashReport(e.Exception);
        e.SetObserved();
    }

    private void CurrentDomain_UnhandledException(object sender, System.UnhandledExceptionEventArgs e)
    {
        if (e.ExceptionObject is System.Exception ex)
        {
            ShowCrashReport(ex);
        }
    }

    private void ShowCrashReport(System.Exception ex)
    {
        System.Windows.Application.Current.Dispatcher.Invoke(() =>
        {
            var errorWin = new GlobalErrorWindow($"CRITICAL CRASH: {ex.Message}\n\n{ex.StackTrace}");
            
            if (System.Windows.Application.Current.MainWindow != null && System.Windows.Application.Current.MainWindow.IsVisible)
            {
                errorWin.Owner = System.Windows.Application.Current.MainWindow;
            }
            
            errorWin.ShowDialog();
        });
    }
}

