using System.Configuration;
using System.Data;
using System.Reflection;
using System.Windows;

namespace BoltFetch;

/// <summary>
/// Interaction logic for App.xaml
/// </summary>
public partial class App : System.Windows.Application
{
    protected override void OnStartup(StartupEventArgs e)
    {
        base.OnStartup(e);

        // Dynamically set version from assembly metadata (auto-generated by csproj)
        var version = System.Reflection.Assembly.GetExecutingAssembly()
            .GetCustomAttribute<System.Reflection.AssemblyInformationalVersionAttribute>()?.InformationalVersion
            ?? "1.0.0";

        // Strip git hash suffix if present (e.g. "1.4.2603.0105+abc123" → "1.4.2603.0105")
        if (version.Contains('+')) version = version[..version.IndexOf('+')];

        this.Resources["Loc_AppVersion"] = $"Version {version}";
    }
}

